[package]
name = "launcher"
description = "The application is launcher for calculator"
authors = ["Ivenin Valentin <iveninvala7@gmail.com>"]
repository = "https://github.com/IOSHED/Iosh__Calculator/"
version = "0.1.3"
edition = "2021"
license = "MIT"

[dependencies]
