name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Check Format
        run: cargo fmt --check

      - name: Run Tests
        run: cargo test --workspace --release

      - name: Run Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Build Release Binaries
        run: |
          cargo build --release --bin launcher
          cargo build --release --bin console

      - name: Prepare Artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path FroCalculator -Force
          Copy-Item target/release/launcher.exe FroCalculator/
          Copy-Item target/release/console.exe FroCalculator/

      - name: Read Release Notes
        id: release_notes
        shell: pwsh
        run: |
          $features = "No new features documented."
          if (Test-Path "RELEASE_NOTES.md") {
              $features = Get-Content "RELEASE_NOTES.md" -Raw
          }
          $features = $features -replace "`r`n", "`n"
          echo "features<<EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "$features" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          echo "EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: FroCalculator ${{ github.ref_name }}
          body: |
            ## Installation Instructions
            To start the application, run either:
            - `FroCalculator\launcher.exe` set default conficurate for calculator
            - `FroCalculator\console.exe` for command-line version

            ## New Features
            ${{ steps.release_notes.outputs.features }}
          files: FroCalculator/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}